# Generated by Django 4.2.2 on 2023-08-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insumo',
            new_name='Presentacion',
        ),
    ]
