# Generated by Django 4.2.2 on 2023-07-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.AlterModelTable(
            name='productopresentacionsprecios',
            table='app_productopresentacions_precios',
        ),
    ]
