# Generated by Django 4.2.2 on 2023-07-25 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_remove_venta_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='/imagen/default.jpg', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(blank=True, default=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_alertas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
