# Generated by Django 4.2.2 on 2023-07-25 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_producto_imagen_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pedido'),
        ),
    ]
