# Generated by Django 4.2.2 on 2023-08-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_producto_presentacions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
