# Generated by Django 4.2.2 on 2023-08-12 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_presentacion_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='caja',
        ),
        migrations.AddField(
            model_name='operacion',
            name='aperturacaja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.aperturacaja'),
            preserve_default=False,
        ),
    ]
