# Generated by Django 4.2.2 on 2023-08-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_operacion_caja_operacion_aperturacaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='monto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
