# Generated by Django 4.2.2 on 2023-08-15 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_lote_monto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recibo',
            new_name='Tipo_recibo',
        ),
        migrations.RemoveField(
            model_name='cobro',
            name='recibo',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='recibo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='empleado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pedido_productopresentacions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.pedido')),
                ('producto_presentacions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto_presentacions')),
            ],
        ),
    ]
