# Generated by Django 4.2.2 on 2023-08-15 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_recibo_tipo_recibo_remove_cobro_recibo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_almacens',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto_almacens',
            name='Producto_presentacions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.producto_presentacions'),
            preserve_default=False,
        ),
    ]
