# Generated by Django 4.2.2 on 2023-08-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_producto_almacens_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_almacens',
            name='cantidadinicial',
        ),
    ]
