# Generated by Django 4.2.2 on 2023-08-15 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_producto_almacens_cantidadinicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.almacen'),
        ),
    ]
