# Generated by Django 4.2.2 on 2023-08-15 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_lote_almacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote_productopresentacions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.lote')),
                ('producto_presentacions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto_presentacions')),
            ],
        ),
    ]
