# Generated by Django 4.2.2 on 2023-08-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_lote_productopresentacions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote_productopresentacions',
            name='cantidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote_productopresentacions',
            name='cnt_cantidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote_productopresentacions',
            name='precio_lote',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pedido_productopresentacions',
            name='cantidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido_productopresentacions',
            name='precio_pedido',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Producto_almacens',
        ),
    ]
