# Generated by Django 4.2.2 on 2023-08-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_lote_productopresentacions_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote_productopresentacions',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido_productopresentacions',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
