# Generated by Django 4.2.2 on 2023-08-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_lote_productopresentacions_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote_productopresentacions',
            old_name='fecha',
            new_name='fecha_caducidad',
        ),
        migrations.RenameField(
            model_name='pedido_productopresentacions',
            old_name='fecha',
            new_name='fecha_caducidad',
        ),
    ]
