# Generated by Django 4.2.2 on 2023-08-17 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_operacion_cobro_operacion_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lote_operacions', to='app.lote'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta_operacions', to='app.venta'),
        ),
        migrations.AlterField(
            model_name='pedido_productopresentacions',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedido_presentacions', to='app.pedido'),
        ),
    ]
