# Generated by Django 4.2.2 on 2023-08-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_operacion_lote_alter_operacion_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='nro_documento',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='lote_productopresentacions',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lote_presentacions', to='app.lote'),
        ),
    ]
