# Generated by Django 4.2.2 on 2023-08-21 15:34

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_cliente_imagen_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('ruc', models.CharField(max_length=11)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('imagen', django_resized.forms.ResizedImageField(blank=True, crop=None, default='/imagen/default_negocio.jpg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[100, None], upload_to='negocio/')),
                ('msg_cliente', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido_productopresentacions',
            name='fecha_caducidad',
        ),
    ]
