# Generated by Django 4.2.2 on 2023-08-29 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_aperturacaja_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='validado',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='aperturacaja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apertura_operacions', to='app.aperturacaja'),
        ),
        migrations.AlterField(
            model_name='producto_presentacions',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_presentaciones', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_ventas', to='app.pedido'),
        ),
    ]
